<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<link rel="stylesheet" type="text/css" href="/css/style.css" />
<link rel="stylesheet" href="/js/dropit/dropit.css" type="text/css" />
<!--[if lte IE 7]>
	<link rel="stylesheet" type="text/css" href="css/ie.css" media="screen" />
<![endif]-->
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.0/jquery.min.js"></script>
<script src="/js/hoverIntent.js"></script>
<script src="/js/jquery.dropdown.js"></script>
<script src="/js/jquery.dropdownPlain.js"></script>