<div id="menu">
<div class="item first">
	<ul class="dropdown">
	  <li>
	    <a href="#">Gifts & Décor</a>
	    <ul>
	      <li><a class="menuitem" href="/willowtree.shtml">Willow Tree</a></li>
	      <li><a class="menuitem" href="/frames.shtml">Frames</a></li>
	      <li><a class="menuitem" href="/gifts_for_men.shtml">Gifts for Men</a></li>
	    </ul>
	  </li>
	</ul>
</div>
<div class="item">
	<ul class="dropdown">
		<li><a href="/funeral_gifts.shtml">Funeral Gifts</a></li>
	</ul>

</div>
<div class="item">
	<ul class="dropdown">
		<li><a href="#">Get Bakin'</a>
			<ul>
				<li><a href="/muffins_cakes.shtml">Muffins & Cakes</a></li>
	            <li><a href="/dip_mixes.shtml">Dip Mixes</a></li>
	            <li><a href="/breads.shtml">Breads</a></li>
	            <li><a href="/sweet_treats.shtml">Sweet Treats</a></li>
			</ul>
		</li>
	</ul>
</div>
<div class="item">
	<ul class="dropdown">
		<li><a href="#">Scentastic'</a>
			<ul>
				<li><a href="/reed_diffusers.shtml">Reed Diffusers</a></li>
				<li><a href="/trilogy_candles.shtml">Trilogy Candles</a></li>
				<li><a href="/medium_jar_candles.shtml">Medium Jar Candles</a></li>
		</li>
	</ul>
</div>
<div class="item">
	<ul class="dropdown">
		<li><a href="#">Toys & Books</a>
			<ul>
				<li><a href="/puzzles.shtml">Puzzles</a></li>
				<li><a href="/on_the_go.shtml">On the Go Fun</a></li>
				<li><a href="/toys.shtml">Toys</a></li>
				<li><a href="/baby_gifts.shtml">Baby Gifts</a></li>
		</li>
	</ul>
</div>
<div class="item">
	<ul class="dropdown">
		<li><a href="/gift_baskets.shtml">Gift Baskets</a></li>
	</ul>
</div>
<div class="item">
	<ul class="dropdown">
		<li><a href="/contact_us.shtml">Contact Us</a></li>
	</ul>
</div>
<div id="facebook"><a href="https://www.facebook.com/pages/Decor-More-from-Rues-Truly/1382127262013725"><img src="/images/facebook.png"></a></div>
</div>