<div id="menu">
<div class="item first">
	<ul class="dropdown">
	  <li>
	    <a href="#">Gifts & Décor</a>
	    <ul>
	      <li><a class="menuitem" href="/willowtree.shtml">Willow Tree</a></li>
	      <li><a class="menuitem" href="/frames.shtml">Frames</a></li>
	      <li><a class="menuitem" href="/gifts_for_men.shmlt">Gifts for Men</a></li>
	    </ul>
	  </li>
	</ul>
</div>
<div class="item">
	<ul class="dropdown">
		<li><a href="#">Funeral Gifts</a></li>
	</ul>

</div>
<div class="item">
	<ul class="dropdown">
		<li><a href="#">Get Bakin'</a>
			<ul>
				<li><a href="#">Muffins & Cakes</a></li>
	            <li><a href="#">Dip Mixes</a></li>
	            <li><a href="#">Breads</a></li>
	            <li><a href="#">Sweet Treats</a></li>
			</ul>
		</li>
	</ul>
</div>
<div class="item">
	<ul class="dropdown">
		<li><a href="#">Scentastic'</a>
			<ul>
				<li><a href="#">Reed Diffusers</a></li>
				<li><a href="#">Trilogy Candles</a></li>
				<li><a href="#">Medium Jar Candles</a></li>
		</li>
	</ul>
</div>
<div class="item">
	<ul class="dropdown">
		<li><a href="#">Toys & Books</a>
			<ul>
				<li><a href="#">Puzzles</a></li>
				<li><a href="#">On the Go Fun</a></li>
				<li><a href="#">Toys</a></li>
				<li><a href="#">Baby Gifts</a></li>
		</li>
	</ul>
</div>
<div class="item">
	<ul class="dropdown">
		<li><a href="#">Gift Baskets</a></li>
	</ul>
</div>
<div class="item">
	<ul class="dropdown">
		<li><a href="#">Contact Us</a></li>
	</ul>
</div>
<div id="facebook"><a href="https://www.facebook.com/pages/Decor-More-from-Rues-Truly/1382127262013725"><img src="/images/facebook.png"></a></div>
</div>